# Generated by Django 5.0.2 on 2024-05-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='user',
        ),
    ]
