# Generated by Django 5.0.2 on 2024-05-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
