# Generated by Django 5.0.2 on 2024-05-20 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_customuser_managers_remove_customuser_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportpost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transport_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
