# Generated by Django 5.0.2 on 2024-05-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transportpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
